import json, datetime

d = json.load(open(r"C:\Users\The Yoda Trader\Desktop\GuitarApp\tools\inventory_data.json"))
lessons = d["lessons"]
pairs = d["pairs"]
generated = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

# lesson grouping (per curriculum §5.0)
support = {21: "technique-support (grip/posture)", 22: "technique-support (transition drill)", 23: "SONG (lives in technique dir — §5.6 gap)"}
spine = [L for L in lessons if L["num"] <= 20]
support_lessons = [L for L in lessons if L["num"] in (21, 22)]
song_lessons = [L for L in lessons if L["num"] == 23]

lines = []
A = lines.append
A(f"# GuitarApp — Lessons & Practice Inventory")
A(f"")
A(f"**Generated:** {generated}  |  **Verified on disk:** yes (all counts match manifests, 0 missing files)")
A(f"")
A(f"## Summary (all verified against `07-app/content/` manifests and files on disk)")
A(f"")
A(f"| Track | Count | Source |")
A(f"|---|---|---|")
A(f"| Technique lessons (spine L01–L20) | {len(spine)} | `lessons/manifest.json` |")
A(f"| Technique-support lessons (L21, L22) | {len(support_lessons)} | `lessons/manifest.json` |")
A(f"| Song lesson shipped as technique (L23) | {len(song_lessons)} | `lessons/manifest.json` |")
A(f"| **Total lessons in manifest** | **{len(lessons)}** | `lessons/manifest.json` |")
A(f"| Practice drills (chord-pair) | {len(pairs)} | `practice/index.json` |")
A(f"| Content packs (blues 3 + country 3) | 6 | `packs/*/manifest.json` |")
A(f"| Teachers (skins) | 3 | `teachers/manifest.json` |")
A(f"")
A(f"**Practice coverage proof:** the {len(pairs)} practice drills are EXACTLY every unique pair of the")
A(f"8 taught chords (C, D, Dm, E, Em, G, A, Am) -> C(8,2) = 28. Full combinatorial coverage, no gaps, no dupes.")
A(f"All drills use engine `one-minute-changes` with a 30/60 changes-per-minute gate (arithmetic, no human QA).")
A(f"")
A(f"## Lessons (23 in manifest)")
A(f"")
A(f"| # | Title | Exercises | New chord | Category |")
A(f"|---|---|---|---|---|")
for L in lessons:
    cat = support.get(L["num"], "technique spine")
    nc = ",".join(L["new_chords"]) if L["new_chords"] else "-"
    A(f"| {L['num']} | {L['title']} | {L['exercises']} | {nc} | {cat} |")
A(f"")
A(f"## Practice drills (28 — every chord pair)")
A(f"")
A(f"All `practice-*.json` exist on disk and match `practice/index.json` (0 missing). Each is `lesson_type: technique`,")
A(f"`engine: one-minute-changes`, `estimated_minutes: 3`, and references the lesson it practices via `practice_of`.")
A(f"")
A(f"| Pair | File | Introduced at |")
A(f"|---|---|---|")
for p in sorted(pairs, key=lambda x: (x["introducedAt"], x["key"])):
    A(f"| {p['key']} | {p['file']} | L{p['introducedAt']} |")
A(f"")
A(f"**Drills by introduction lesson:**")
A(f"- L3: C::Em")
A(f"- L6: Em::G, C::G")
A(f"- L7: D::Em, C::D, D::G")
A(f"- L8: A::Em, A::C, A::G, A::D")
A(f"- L9: Am::Em, Am::C, Am::G, Am::D, A::Am")
A(f"- L16: E::Em, C::E, E::G, D::E, A::E, Am::E")
A(f"- L17: Dm::Em, C::Dm, Dm::G, D::Dm, A::Dm, Am::Dm, Dm::E")
A(f"")
A(f"## Content packs (6 lessons, outside the 20-group spine)")
A(f"")
A(f"- **Blues pack** (`packs/blues/`): B1 E7, B2 A7, B3 12-bar — teacher T4")
A(f"- **Country pack** (`packs/country/`): C1 G, C2 C, C3 I–IV–V — teacher T5")
A(f"- Manifests present and list their files; both include a teacher asset JSON.")
A(f"")
A(f"## Teachers (3 skins, shared curriculum)")
A(f"")
A(f"- T1 Maggie Cole, T2 Ellis Nakamura, T3 Ray Boudreaux (`teachers/manifest.json`).")
A(f"")
A(f"## Known gaps (tracked, non-blocking)")
A(f"")
A(f"1. **Songs category not yet realized on disk (LOW, §5.6).** Curriculum mandates songs as a separate")
A(f"   category. `05-content/songs/` holds 2 seed docs (S1 Em→easyC, S2 G–D–Em–C) but `07-app/content/songs/`")
A(f"   does not exist. L23 \"Your First 3-Chord Song\" still ships inside the technique lessons dir (chords G, Em, easyC).")
A(f"   Closing action: create `07-app/content/songs/`, move L23 there. No effect on the 20-group spine or 1:1 ratio.")
A(f"2. **All 28 practice drills use only the `one-minute-changes` engine.** The §5.2 menu defines 11 drill types")
A(f"   (Chord-Perfect, Air Changes, Tempo Loop, Wait-To-Play, Weak-Pair Review, etc.); only the counted")
A(f"   changes drill is generated so far. Practice breadth is the next build item, not a correctness gap.")
A(f"3. **No dedicated Practice Mode UI** (competitor parity gap, noted in curriculum §3) — drills exist as")
A(f"   content; no standalone 'just practice' surface yet.")
A(f"")
A(f"## Verification status")
A(f"")
A(f"- Manifest↔files: all 23 lesson files + 28 practice files present (0 missing).")
A(f"- Ship gate `node run-chord-check.js` lives at `06-prototypes/step0/schema/`; practice generation at")
A(f"  `06-prototypes/practice-engine/` (17 tests per curriculum review). Re-run those gates to assert 0 errors/0 warnings.")
A(f"- This inventory is a static count/coverage report; it does not re-run the audio/arithmetic gates.")
A(f"")
A(f"---\n*Produced by `tools/inventory_scan.py` + `tools/gen_inventory_report.py`.*")

report = "\n".join(lines)
out = r"C:\Users\The Yoda Trader\Desktop\GuitarApp\04-validation\LESSONS-PRACTICE-INVENTORY-2026-08-13.md"
open(out, "w").write(report)
print("WROTE", out, "(", len(report), "bytes )")
print("lessons:", len(lessons), "pairs:", len(pairs))
