import re, pathlib
base = pathlib.Path(r"C:/Users/The Yoda Trader/Desktop/GuitarApp/06-prototypes/practice-engine")
src = (base / "listener-real.mjs").read_text(encoding="utf-8")
body = re.sub(r'export\s+(function|const)', r'\1', src)
header = """// listener-twin.js — BROWSER twin of listener-real.mjs (file://-safe, NO ES import).
// Generated byte-faithful from the TESTED module so the browser path uses identical
// FFT / pitch-class / classify math. Exposes window.GuitarAppListener.
// Real pitch detection = built-in CREPE-class FFT (runs in-browser, on-device, audio
// never leaves the device). Swap in basic-pitch/CREPE later via the pitchDetector hook.
(function (global) {
"""
footer = """
  global.GuitarAppListener = {
    CHORD_NOTES, chordPitchClasses, freqToPitchClass, detectPitchClasses,
    classifyStrum, createListenerReal, analyzeAudio
  };
})(typeof window !== 'undefined' ? window : globalThis);
"""
out = header + body + footer
(base / "listener-twin.js").write_text(out, encoding="utf-8")
print("wrote listener-twin.js", len(out), "bytes")
left = re.findall(r'export\s+(?!function|const)', out)
print("stray exports:", left)
